### ISSUE TITLE
v0.3.0 generates invalid code from grammar.

### ISSUE THREAD

**Issue by SuperDoxin** [PhilippeSigaud/Pegged#181]
given this grammar:

    assemblyFile:
    list <- line+ EOF
    line <- :WS? comment / instruction
    comment <- :';' ~((!'\n' .)*) EOL / EOL
    label_list <- (label :WS?)*
    label <- ~(!opcode ([a-zA-Z_] [a-zA-Z0-9_]*))
    operation <- opcode :'.' modifier / opcode
    opcode <- 'DAT' / 'MOV' / 'ADD' / 'SUB' / 'MUL' / 'DIV' / 'MOD' / 'JMP' /
             'JMZ' / 'JMN' / 'DJN' / 'CMP' / 'SLT' / 'SPL' / 'SNE' / 'SEQ' / 'ORG' / 'EQU' / 
             'END'
    modifier <- 'AB' / 'BA' / 'A' / 'B' / 'F' / 'X' / 'I' / eps
    mode <- '#' / '$' / '@' / '<' / '>' / '{' / '}' / '*' / eps
    expr <- '(' expr ')' / term '%' expr / term '/' expr / term '*' expr / term '-' expr /
           term '+' expr / term
    term <- label / number / expr
    number <- whole_number / signed_integer
    signed_integer <~ '+' whole_number / '-' whole_number
    whole_number <~ [0-9]+
    WS <- ' '+
    EOL <- :'\n' / EOF
    EOF <- !.
    
    instruction <- label_list :WS? operation :WS? mode :WS? expr :WS? ',' :WS? mode :WS? expr :WS? comment / 
                   label_list :WS? operation :WS? mode :WS? expr :WS? comment

it generates unreachable code, which is a warning, which under dub defaults to an error.

now I'm sure I did something wrong here, but I can't figure out what's going on inside that mixin.

note that this exact same grammar *did* work using 0.2.1

**Comment by veelo** [comment]
I cannot reproduce this with dmd 2.068.2. What compiler are you using, compile options, OS?

**Comment by veelo** [comment]
You may be able to identify the unreachable code by importing the parser as a module instead of a mixin.

Generate the module with an `rdmd` on something like
```
import pegged.grammar;

enum asmGrammar=`...`;

void main()
{
	asModule!()("asmparser", "asmparser", asmGrammar);
}
```

**Comment by SuperDoxin** [comment]
doing a small test program like that just fails to link:

    $ dub run
        Fetching pegged 0.3.0 (getting selected version)...
        Placing pegged 0.3.0 to /home/lieuwe/.dub/packages/...
        Performing "debug" build using dmd for x86_64.
        pegged 0.3.0: building configuration "library"...
        temp ~master: building configuration "application"...
        Linking...
        .dub/build/application-debug-linux.posix-x86_64-dmd_2069-E569BA6FE04E874B77B8F9C96FB25CF4/temp.o: In function `_D6pegged7grammar44__T7grammarVE6pegged7grammar11Memoizationi1Z7grammarFAyaZ21leftRecursionStoppersMFNaZAAya':
        /home/lieuwe/Desktop/dlang/temp/../../../.dub/packages/pegged-0.3.0/pegged/grammar.d:115: undefined reference to `_D6pegged13introspection8ruleInfoFNaS6pegged3peg9ParseTreeZHAyaS6pegged13introspection8RuleInfo'
        collect2: error: ld returned 1 exit status
        --- errorlevel 1
        dmd failed with exit code 1.


I'm using DMD64 D Compiler v2.069.1 on linux. compile options left at dubs defaults.

**Comment by veelo** [comment]
> fails to link

This looks like #172, which should be fixed in 0.3.0. `introspection.d` was added to the `Makefile` in b7fb6022b2127ff17c7543526c248d9948ceee07. Can dub be instructed to show what it does when it builds the library?

**Comment by SuperDoxin** [comment]
running it verbose gives this output:

    $ dub build -v
        Using dub registry url 'http://code.dlang.org/'
        Refreshing local packages (refresh existing: true)...
        Looking for local package map at /var/lib/dub/packages/local-packages.json
        Looking for local package map at /home/lieuwe/.dub/packages/local-packages.json
        Note: Failed to determine version of package temp at .. Assuming ~master.
        Refreshing local packages (refresh existing: false)...
        Looking for local package map at /var/lib/dub/packages/local-packages.json
        Looking for local package map at /home/lieuwe/.dub/packages/local-packages.json
        Missing dependency pegged 0.3.0 of temp
        Checking for missing dependencies.
        Using fixed selection pegged 0.3.0
        Fetching pegged 0.3.0 (getting selected version)...
        Acquiring package zip file
        Found download URL: 'http://code.dlang.org/packages/pegged/0.3.0.zip'
        Placing pegged 0.3.0 to /home/lieuwe/.dub/packages/...
        Placing package 'pegged' version '0.3.0' to location '/home/lieuwe/.dub/packages/pegged-0.3.0' from file '/tmp/pegged-0.3.0.zip'
        Copying all files...
        48 file(s) copied.
        Refreshing local packages (refresh existing: false)...
        Looking for local package map at /var/lib/dub/packages/local-packages.json
        Looking for local package map at /home/lieuwe/.dub/packages/local-packages.json
        Found dependency pegged 0.3.0
        Checking for upgrades.
        Using cached upgrade results...
        Generating using build
        Generate target temp (executable /home/lieuwe/Desktop/dlang/temp temp)
        Generate target pegged (staticLibrary /home/lieuwe/.dub/packages/pegged-0.3.0 pegged)
        Performing "debug" build using dmd for x86_64.
        Target '/home/lieuwe/.dub/packages/pegged-0.3.0/.dub/build/library-debug-linux.posix-x86_64-dmd_2069-35A6B07FDAA372B4E8134B4DACC4C232/libpegged.a' doesn't exist, need rebuild.
        pegged 0.3.0: building configuration "library"...
        dmd -lib -of../../../.dub/packages/pegged-0.3.0/.dub/build/library-debug-linux.posix-x86_64-dmd_2069-35A6B07FDAA372B4E8134B4DACC4C232/libpegged.a -debug -g -ignore -w -version=Have_pegged -I../../../.dub/packages/pegged-0.3.0 ../../../.dub/packages/pegged-0.3.0/pegged/dynamic/grammar.d ../../../.dub/packages/pegged-0.3.0/pegged/dynamic/peg.d ../../../.dub/packages/pegged-0.3.0/pegged/grammar.d ../../../.dub/packages/pegged-0.3.0/pegged/parser.d ../../../.dub/packages/pegged-0.3.0/pegged/peg.d ../../../.dub/packages/pegged-0.3.0/pegged/tester/grammartester.d ../../../.dub/packages/pegged-0.3.0/pegged/tester/testerparser.d -vcolumns
        Copying target from /home/lieuwe/.dub/packages/pegged-0.3.0/.dub/build/library-debug-linux.posix-x86_64-dmd_2069-35A6B07FDAA372B4E8134B4DACC4C232/libpegged.a to /home/lieuwe/.dub/packages/pegged-0.3.0
        Target '/home/lieuwe/Desktop/dlang/temp/.dub/build/application-debug-linux.posix-x86_64-dmd_2069-E569BA6FE04E874B77B8F9C96FB25CF4/temp' doesn't exist, need rebuild.
        temp ~master: building configuration "application"...
        dmd -c -of.dub/build/application-debug-linux.posix-x86_64-dmd_2069-E569BA6FE04E874B77B8F9C96FB25CF4/temp.o -debug -g -w -version=Have_temp -version=Have_pegged -Isource/ -I../../../.dub/packages/pegged-0.3.0 source/app.d -vcolumns
        Linking...
        dmd -of.dub/build/application-debug-linux.posix-x86_64-dmd_2069-E569BA6FE04E874B77B8F9C96FB25CF4/temp .dub/build/application-debug-linux.posix-x86_64-dmd_2069-E569BA6FE04E874B77B8F9C96FB25CF4/temp.o ../../../.dub/packages/pegged-0.3.0/libpegged.a -L--no-as-needed -g
        .dub/build/application-debug-linux.posix-x86_64-dmd_2069-E569BA6FE04E874B77B8F9C96FB25CF4/temp.o: In function `_D6pegged7grammar44__T7grammarVE6pegged7grammar11Memoizationi1Z7grammarFAyaZ21leftRecursionStoppersMFNaZAAya':
        /home/lieuwe/Desktop/dlang/temp/../../../.dub/packages/pegged-0.3.0/pegged/grammar.d:115: undefined reference to `_D6pegged13introspection8ruleInfoFNaS6pegged3peg9ParseTreeZHAyaS6pegged13introspection8RuleInfo'
        collect2: error: ld returned 1 exit status
        --- errorlevel 1
        FAIL .dub/build/application-debug-linux.posix-x86_64-dmd_2069-E569BA6FE04E874B77B8F9C96FB25CF4/ temp executable
        dmd failed with exit code 1.

so it seems introspection.d isn't included in the build at all. I'm not sure why dub isn't including it, or how to tell it to include it.

**Comment by veelo** [comment]
Thanks.

There is a line missing in the `"sourceFiles"` section of `package.json` of Pegged:
```
        "pegged/introspection.d",
```
Sorry for having overlooked it.

@PhilippeSigaud are you able to fix this or do you need a PR?

**Comment by veelo** [comment]
> @PhilippeSigaud are you able to fix this or do you need a PR?

Well, I am sure you are *able*, I meant whether you would have an opportunity to do it ;-) But I would guess that this needs a small bump in the version to work in `dub`, which needs your attention anyway.

**Comment by PhilippeSigaud** [comment]
I pushed a commit to add introspection.d in the package.json of Pegged.
I don't have dub on the machine I'm using, can someone test to see if that works now?

**Comment by SuperDoxin** [comment]
yep, using the master branch compiles now.

**Comment by PhilippeSigaud** [comment]
OK, I'll push a 'v0.3.1' tag.

**Comment by PhilippeSigaud** [comment]
There is now a v0.3.1 tag. That will be caught by code.dlang.org tonight.

**Comment by veelo** [comment]
Thanks.
@SuperDoxin what about the unreachable code, is that still a problem? I think we'd need a bit more help to reproduce what you are getting. A self-contained example would be great.

**Comment by SuperDoxin** [comment]
so far it seems to be behaving on that regard. I haven't the foggiest on how I managed to cause that in the first place.

right now I'm trying to figure out why the generated code is segfaulting, but maybe I should open a new issue for that?

**Comment by veelo** [comment]
Segfault can be to an infinite recursion. Pegged should be a lot safer against that now, but who knows. But that would be another issue.

I think this can be closed then.

**Comment by SuperDoxin** [comment]
alright, I'll be opening a new issue on that topic then. thanks a bunch for the help so far.
